networks:
  redis-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
services:
  nginx:
    image: nginx:1.23.0
    container_name: nginx
    networks:
      redis-network:
        ipv4_address: 172.18.0.9