networks:
  nginx-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
services:
  nginx:
    image: nginx:1.23.0
    container_name: nginx
    networks:
      nginx-network:
        ipv4_address: 172.18.0.10
    volumes:
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/nginx/conf:/etc/nginx
      - /Volumes/data/volumes/nginx/log:/var/log/nginx
    ports:
      - 80:80