version: "3"
# docker-compose -f docker-compose-host.yaml up

services:
  redis-node-01:
    image: redis:7.0.2
    container_name: redis-node-01
    command: /scripts/redis/redis_cluster_master.sh
    network_mode: "host"
    volumes:
      - /Volumes/data/suzaku/volumes/cluster/redis/redis-node-01:/data
      - ./configs/cluster/redis/7001/redis.conf:/usr/local/etc/redis/redis.conf
      - ./scripts/cluster/redis/redis_cluster_master.sh:/scripts/redis/redis_cluster_master.sh
    depends_on:
      - redis-node-02
      - redis-node-03
      - redis-node-04
      - redis-node-05
      - redis-node-06
      - redis-node-07
      - redis-node-08

  redis-node-02:
    image: redis:7.0.2
    container_name: redis-node-02
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    volumes:
      - /Volumes/data/suzaku/volumes/cluster/redis/redis-node-02:/data
      - ./configs/cluster/redis/7002/redis.conf:/usr/local/etc/redis/redis.conf
  redis-node-03:
    image: redis:7.0.2
    container_name: redis-node-03
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    volumes:
      - /Volumes/data/suzaku/volumes/cluster/redis/redis-node-03:/data
      - ./configs/cluster/redis/7003/redis.conf:/usr/local/etc/redis/redis.conf
  redis-node-04:
    image: redis:7.0.2
    container_name: redis-node-04
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    volumes:
      - /Volumes/data/suzaku/volumes/cluster/redis/redis-node-04:/data
      - ./configs/cluster/redis/7004/redis.conf:/usr/local/etc/redis/redis.conf
  redis-node-05:
    image: redis:7.0.2
    container_name: redis-node-05
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    volumes:
      - /Volumes/data/suzaku/volumes/cluster/redis/redis-node-05:/data
      - ./configs/cluster/redis/7005/redis.conf:/usr/local/etc/redis/redis.conf
  redis-node-06:
    image: redis:7.0.2
    container_name: redis-node-06
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    volumes:
      - /Volumes/data/suzaku/volumes/cluster/redis/redis-node-06:/data
      - ./configs/cluster/redis/7006/redis.conf:/usr/local/etc/redis/redis.conf
  redis-node-07:
    image: redis:7.0.2
    container_name: redis-node-07
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    volumes:
      - /Volumes/data/suzaku/volumes/cluster/redis/redis-node-07:/data
      - ./configs/cluster/redis/7007/redis.conf:/usr/local/etc/redis/redis.conf
  redis-node-08:
    image: redis:7.0.2
    container_name: redis-node-08
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    volumes:
      - /Volumes/data/suzaku/volumes/cluster/redis/redis-node-08:/data
      - ./configs/cluster/redis/7008/redis.conf:/usr/local/etc/redis/redis.conf