version: "3"

services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - teamgram-net
    volumes:
      - ./docker/scripts/mysql:/docker-entrypoint-initdb.d
      - /Volumes/data/teamgram/volumes/mysql/data:/var/lib/mysql
      #- /Volumes/data/teamgram/volumes/mysql/conf:/etc/mysql
      - /Volumes/data/teamgram/volumes/mysql/mysql-files:/var/lib/mysql-files
      - /Volumes/data/teamgram/volumes/mysql/log:/var/log/mysql
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: teamgram2022
      ALLOW_HOST: "%"

networks:
  teamgram-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/24