version: '3'
# chmod +x *
# chmod -R 777 scripts

services:
  nginx:
    image: nginx:1.23.0
    container_name: nginx
    ports:
      - 3307:3307
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/scripts/nginx:/docker-entrypoint-init-mysql.d #挂载master脚本
    command:
      - "mkdir -p /docker-entrypoint-init-mysql.d"
      - "chmod +x /docker-entrypoint-init-mysql.d/*"
      - "./docker-entrypoint-init-mysql.d/master.sh"
    networks:
      mysql-network:
        ipv4_address: "10.10.10.2"
    depends_on:
      - mysql-master-01
      - mysql-master-02
      - mysql-slave-01
      - mysql-slave-02

  mysql-master-01:
    image: mysql:8.0.29
    container_name: mysql-master-01
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MASTER_SYNC_USER: "sync_admin" #设置脚本中定义的用于同步的账号
      MASTER_SYNC_PASSWORD: "123456" #设置脚本中定义的用于同步的密码
      ADMIN_USER: "root" #当前容器用于拥有创建账号功能的数据库账号
      ADMIN_PASSWORD: "123456"
      ALLOW_HOST: "10.10.%.%" #允许同步账号的host地址
      TZ: "Asia/Shanghai" #解决时区问题
    ports:
      - 13306:3306
    networks:
      mysql-network:
        ipv4_address: "10.10.10.10" #固定ip，因为从库在连接master的时候，需要设置host
    privileged: true
    volumes:
      - $PWD/mycnf/master-01/my.cnf:/etc/my.cnf
      - $PWD/scripts/master-01:/docker-entrypoint-init-mysql.d #挂载master脚本
      - /Volumes/data/suzaku/volumes/cluster/mysql/master-01/data:/var/lib/mysql
    command:
      - "--server-id=10"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--log-bin=mysql-bin"
      - "--sync_binlog=1"
      - "mkdir -p /docker-entrypoint-init-mysql.d"
      - "chmod +x /docker-entrypoint-init-mysql.d/*"
      - "./docker-entrypoint-init-mysql.d/create_sync_user.sh"

  mysql-master-02:
    image: mysql:8.0.29
    container_name: mysql-master-02
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MASTER_SYNC_USER: "sync_admin" #设置脚本中定义的用于同步的账号
      MASTER_SYNC_PASSWORD: "123456" #设置脚本中定义的用于同步的密码
      ADMIN_USER: "root" #当前容器用于拥有创建账号功能的数据库账号
      ADMIN_PASSWORD: "123456"
      ALLOW_HOST: "10.10.%.%" #允许同步账号的host地址
      TZ: "Asia/Shanghai" #解决时区问题
    ports:
      - 13307:3306
    networks:
      mysql-network:
        ipv4_address: "10.10.10.100" #固定ip，因为从库在连接master的时候，需要设置host
    privileged: true
    volumes:
      - $PWD/mycnf/master-02/my.cnf:/etc/my.cnf
      - $PWD/scripts/master-02:/docker-entrypoint-init-mysql.d #挂载master脚本
      - /Volumes/data/suzaku/volumes/cluster/mysql/master-02/data:/var/lib/mysql
    command:
      - "--server-id=100"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--log-bin=mysql-bin"
      - "--sync_binlog=1"
      - "mkdir -p /docker-entrypoint-init-mysql.d"
      - "chmod +x /docker-entrypoint-init-mysql.d/*"
      - "./docker-entrypoint-init-mysql.d/create_sync_user.sh"

  mysql-slave-01:
    image: mysql:8.0.29
    container_name: mysql-slave-01
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      SLAVE_SYNC_USER: "sync_admin" #用于同步的账号，由master创建
      SLAVE_SYNC_PASSWORD: "123456"
      ADMIN_USER: "root"
      ADMIN_PASSWORD: "123456"
      MASTER_HOST: "10.10.10.10" #master地址，开启主从同步需要连接master
      TZ: "Asia/Shanghai" #设置时区
    ports:
      - 13308:3306
    networks:
      mysql-network:
        ipv4_address: "10.10.10.11" #固定ip
    privileged: true
    volumes:
      - $PWD/mycnf/slave-01/my.cnf:/etc/my.cnf
      - $PWD/scripts/slave-01:/docker-entrypoint-init-mysql.d #挂载slave脚本
      - /Volumes/data/suzaku/volumes/cluster/mysql/slave-01/data:/var/lib/mysql
    command:
      - "--server-id=11"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "mkdir -p /docker-entrypoint-init-mysql.d"
      - "chmod +x /docker-entrypoint-init-mysql.d/*"
      - "./docker-entrypoint-init-mysql.d/slave.sh"

  mysql-slave-02:
    image: mysql:8.0.29
    container_name: mysql-slave-02
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      SLAVE_SYNC_USER: "sync_admin"
      SLAVE_SYNC_PASSWORD: "123456"
      ADMIN_USER: "root"
      ADMIN_PASSWORD: "123456"
      MASTER_HOST: "10.10.10.100"
      TZ: "Asia/Shanghai"
    ports:
      - 13309:3306
    networks:
      mysql-network:
        ipv4_address: "10.10.10.101" #固定ip
    privileged: true
    volumes:
      - $PWD/mycnf/slave-02/my.cnf:/etc/my.cnf
      - $PWD/scripts/slave-02:/docker-entrypoint-init-mysql.d #挂载slave脚本
      - /Volumes/data/suzaku/volumes/cluster/mysql/slave-02/data:/var/lib/mysql
    command: #这里需要修改server-id，保证每个mysql容器的server-id都不一样
      - "--server-id=101"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "mkdir -p /docker-entrypoint-init-mysql.d"
      - "chmod +x /docker-entrypoint-init-mysql.d/*"
      - "./docker-entrypoint-init-mysql.d/slave.sh"

networks:
  mysql-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/16"